### ISSUE TITLE
Don't add additional line breaks in they already exist

### ISSUE THREAD

**Issue by mattgd** [sgreene570/readme-generator#5]
Running the script multiple times on the file causes extra line breaks to be added.

**Comment by sgreene570** [comment]
I'll fix this shortly. Thanks.

**Comment by mattgd** [comment]
Just fixed it, but I'll stash my changes and see how you tackle it.

**Comment by sgreene570** [comment]
I'm actually not sure about the best way to do this

**Comment by mattgd** [comment]
I was also having trouble thinking about how to do this without messing with the user's readme format, but for right now I just have it remove br tags and not add empty lines. Thoughts?

**Comment by sgreene570** [comment]
thats fine by me!

**Comment by mattgd** [comment]
Added a fix in 51816af. May not be perfect, but closing this for now.
