### ISSUE TITLE
Add command to replace README.md contents with the OUTPUT.md contents

### ISSUE THREAD

**Issue by mattgd** [sgreene570/readme-generator#8]

**Comment by sgreene570** [comment]
Would be a good idea to save a backup of the original as readme.backup or something (maybe a hidden file).

**Comment by mattgd** [comment]
Yeah, good idea. I'll work on this.

**Comment by mattgd** [comment]
Implemented, will be pushed with other changes soon.

**Comment by mattgd** [comment]
Implemented in 625f5f8. Now the user is prompted to replace, or optionally they can use the -f argument to not be asked.
